CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('MEDICO', 'ENFERMEIRO', 'PACIENTE'))
);

CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    observacoes VARCHAR(1000),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_consultas_paciente FOREIGN KEY (paciente_id) REFERENCES users (id),
    CONSTRAINT fk_consultas_medico FOREIGN KEY (medico_id) REFERENCES users (id),
    CONSTRAINT ck_consultas_status CHECK (status IN ('AGENDADA', 'REALIZADA', 'CANCELADA'))
);

CREATE INDEX idx_consultas_paciente_data_hora
    ON consultas (paciente_id, data_hora);

CREATE INDEX idx_consultas_medico_data_hora
    ON consultas (medico_id, data_hora);

CREATE INDEX idx_consultas_paciente_status
    ON consultas (paciente_id, status);
