CREATE TABLE notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    destinatario VARCHAR(255),
    tipo VARCHAR(32) NOT NULL,
    mensagem VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    data_envio TIMESTAMP NOT NULL,
    CONSTRAINT ck_notificacoes_tipo CHECK (tipo IN ('CONSULTA_CRIADA', 'CONSULTA_EDITADA')),
    CONSTRAINT ck_notificacoes_status CHECK (status IN ('ENVIADA', 'FALHA'))
);

CREATE INDEX idx_notificacoes_paciente ON notificacoes (paciente_id);
CREATE INDEX idx_notificacoes_consulta ON notificacoes (consulta_id);
